server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO}
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
          default-label: ${GITHUB_BRANCH}